// Прямые импорты иконок — совместимо с любой версией Vite
import {
  // Навигация
  Home,
  Library,
  FileText,
  Calendar,
  MessageCircle,
  BarChart2,
  User,
  Users,
  Layers,
  Folder,
  Settings,

  // Действия
  Bell,
  Search,
  Plus,
  Check,
  X,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  MoreHorizontal,
  MoreVertical,
  Download,
  Upload,
  Link,
  ExternalLink,
  Edit,
  Edit2,
  Trash,
  Trash2,
  Copy,
  RefreshCw,
  Filter,

  // Статусы / инфо
  Info,
  AlertCircle,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  HelpCircle,
  Clock,
  Award,

  // Медиа
  Image,
  File,
  Paperclip,
  Mail,
  Phone,
  Send,

  // Прочее
  Moon,
  Sun,
  Menu,
  LogOut,
  LogIn,
  Lock,
  Eye,
  EyeOff,
  GraduationCap,
  BookOpen,
  Book,
  Inbox,
  CheckCheck,
  Star,
  Play,
  Pause,
  Volume2,
  Video,
  Mic,
} from 'lucide-react';

const MAP = {
  home: Home,
  library: Library,
  'file-text': FileText,
  calendar: Calendar,
  'message-circle': MessageCircle,
  'bar-chart-2': BarChart2,
  user: User,
  users: Users,
  layers: Layers,
  folder: Folder,
  settings: Settings,

  bell: Bell,
  search: Search,
  plus: Plus,
  check: Check,
  x: X,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  download: Download,
  upload: Upload,
  link: Link,
  'external-link': ExternalLink,
  edit: Edit,
  'edit-2': Edit2,
  trash: Trash,
  'trash-2': Trash2,
  copy: Copy,
  'refresh-cw': RefreshCw,
  filter: Filter,

  info: Info,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'check-circle-2': CheckCircle2,
  'x-circle': XCircle,
  'help-circle': HelpCircle,
  clock: Clock,
  award: Award,

  image: Image,
  file: File,
  paperclip: Paperclip,
  mail: Mail,
  phone: Phone,
  send: Send,

  moon: Moon,
  sun: Sun,
  menu: Menu,
  'log-out': LogOut,
  'log-in': LogIn,
  lock: Lock,
  eye: Eye,
  'eye-off': EyeOff,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  book: Book,
  inbox: Inbox,
  'check-check': CheckCheck,
  star: Star,
  play: Play,
  pause: Pause,
  'volume-2': Volume2,
  video: Video,
  mic: Mic,
};

export default function Icon({ name, size = 18, strokeWidth = 2, ...rest }) {
  const Cmp = MAP[name] || HelpCircle;
  return <Cmp size={size} strokeWidth={strokeWidth} {...rest} />;
}